FROM openjdk:17.0.2-jdk

LABEL maintainer="dk"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

ENV SPRING_PROFILES_ACTIVE=beta

ENV JAVA_OPTS="\
-XX:+UseG1GC \
-Dfile.encoding=UTF-8 \
-Dsun.jnu.encoding=UTF-8 \
"

WORKDIR /app
COPY target/globox-notification-service-*.jar /app/app.jar

EXPOSE 12028 22028 23028
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]